blank_issues_enabled: false
contact_links:
    - name: ðŸ”’ Report a Security Vulnerability
      url: https://github.com/humanwhocodes/gitignore-to-minimatch/security/advisories/new
      about: Privately report a security vulnerability to the team
